name: Deploy to EC2

on:
  push:
    branches:
      - main  # The branch to trigger the workflow from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Ensure the .ssh directory exists
        run: mkdir -p ~/.ssh

      - name: Check Runner Username
        run: |
          echo "RUNNER USERNAME IS : $(whoami)"
      
      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/TeymiSEC2.pem
          chmod 400 ~/.ssh/TeymiSEC2.pem 
          ssh-keygen -y -f ~/.ssh/TeymiSEC2.pem > ~/.ssh/TeymiSEC2.pub
      
      - name: Add EC2 to known hosts with ssh-keyscan
        run: ssh-keyscan -H ${{secrets.EC2IPADDRESS}} >> ~/.ssh/known_hosts
              
      - name: List contents of .ssh directory
        run: ls -laR /home/runner/.ssh/

      - name: Set up SSH agent
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/TeymiSEC2.pem

      - name: Debug - Print EC2 info
        run: |
          echo "EC2NAME=${{secrets.EC2NAME}}"
          echo "EC2PUBLICIPDNS=${{secrets.EC2PUBLICIPDNS}}"

      - name: Deploy to EC2
        run: ssh -o StrictHostKeyChecking=no -v ${{secrets.EC2NAME}}@${{secrets.EC2PUBLICIPDNS}} "cd ${{secrets.PATHOFAPP}} && git pull origin main && ./deploy.sh"
