name: Deploy to EC2

on:
  push:
    branches:
      - main  # The branch to trigger the workflow from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Ensure the .ssh directory exists
        run: mkdir -p ~/.ssh

      - name: Add EC2 known host from secret
        run: echo "${{ secrets.EC2_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Add EC2 to known hosts with ssh-keyscan
        run: ssh-keyscan -H ${{secrets.EC2IPADDRESS}} >> ~/.ssh/known_hosts

      - name: List contents of .ssh directory
        run: ls -la ~/.ssh/

      - name: Check Runner Username
        run: | 
          echo "RUNNER USERNAME IS : $(whoami)"

      - name: Set up SSH agent
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -

      - name: Debug - Print EC2 info
        run: |
          echo "EC2NAME=${{secrets.EC2NAME}}"
          echo "EC2PUBLICIPDNS=${{secrets.EC2PUBLICIPDNS}}"

      - name: Deploy to EC2
        run: ssh -v ${{secrets.EC2NAME}}@${{secrets.EC2PUBLICIPDNS}} "cd ${{secrets.PATHOFAPP}} && git pull origin main && ./deploy.sh"
