name: Deploy to EC2

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Create known_hosts file
        run: mkdir -p ~/.ssh && touch ~/.ssh/known_hosts

      - name: Add EC2 to known hosts
        run: |
          # Ensure the .ssh directory exists
          mkdir -p ~/.ssh

          # Append the EC2 host to known_hosts
          ssh-keyscan -H ${{secrets.EC2IPADDRESS}} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          # Configure the SSH agent and add the private key
          echo "${{ secrets.EC2PRIVATEKEY }}" | tr -d '\r' | ssh-add -
          
          # Make sure the key is protected
          chmod 600 ~/.ssh/id_rsa

          # SSH into the EC2 instance and execute commands
          ssh -i ~/.ssh/id_rsa ${{secrets.EC2NAME}}@${{secrets.EC2PUBLICIPDNS}} "cd ${{secrets.PATHOFAPP}} && git pull origin main && ./deploy.sh"
