name: Deploy to EC2

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          node-version: 16

      - name: SSH into EC2 and deploy
        run: |
          ssh -i ${{secrets.EC2PRIVATEKEY}} ${{secrets.EC2NAME}}@${{secrets.EC2IPADDRESS}} "cd ${{secrets.PATHOFAPP}} && git pull origin main && ./deploy.sh"
