name: Deploy to EC2

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Create known_hosts file
        run: mkdir -p ~/.ssh && touch ~/.ssh/known_hosts

      - name: Add EC2 to known hosts
        run: |
          # Ensure the .ssh directory exists
          mkdir -p ~/.ssh

          # Append the EC2 host to known_hosts
          ssh-keyscan -H ${{secrets.EC2IPADDRESS}} >> ~/.ssh/known_hosts

      - name: List contents of .ssh directory
        run: ls -la ~/.ssh/

      - name: Check Runner Username
        run: |
          whoami
          echo "RUNNER USERNAME IS : $(whoami)"

      - name: Set up SSH agent
        run: |
          # Start the SSH agent
          eval $(ssh-agent -s)
          
          # Add the SSH private key to the agent
          echo "${{ secrets.EC2PRIVATEKEY }}" | tr -d '\r' | ssh-add -

          # Make sure the key is protected
          chmod 600 /home/runner/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          # SSH into the EC2 instance and execute commands
          ssh -i /home/runner/.ssh/id_rsa ${{secrets.EC2NAME}}@${{secrets.EC2PUBLICIPDNS}} "cd ${{secrets.PATHOFAPP}} && git pull origin main && ./deploy.sh"
